/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perc7p3yudha;

/**
 *
 * @author ktyudha
 */
public class KartuSim extends javax.swing.JFrame {
    
    double total = 0;
    double totAll =0;
    double simpati, im3, axis, xl;
    /**
     * Creates new form KartuSim
     */
    public KartuSim() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        optSimpati = new javax.swing.JCheckBox();
        optIm3 = new javax.swing.JCheckBox();
        optAxis = new javax.swing.JCheckBox();
        optXl = new javax.swing.JCheckBox();
        teSimpati = new javax.swing.JTextField();
        teIm3 = new javax.swing.JTextField();
        teAxis = new javax.swing.JTextField();
        teXl = new javax.swing.JTextField();
        cbMethod = new javax.swing.JComboBox<>();
        btnProses = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        labelTot = new javax.swing.JLabel();
        TotHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Perhitungan Harga Grosir");

        optSimpati.setText("Simpati [Rp10.000] ");

        optIm3.setText("IM3 [Rp9.000] ");

        optAxis.setText("AXIS [Rp8.000] ");

        optXl.setText("XL [Rp7.000] ");

        cbMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "1 Minggu", "1 Bulan" }));
        cbMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMethodActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        labelTot.setText("Total : Rp");

        TotHarga.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optSimpati)
                            .addComponent(optIm3)
                            .addComponent(optAxis)
                            .addComponent(optXl))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teSimpati, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(teIm3)
                            .addComponent(teAxis)
                            .addComponent(teXl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProses)
                    .addComponent(btnClear))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optSimpati)
                    .addComponent(teSimpati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optIm3)
                    .addComponent(teIm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optAxis)
                    .addComponent(teAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optXl)
                    .addComponent(teXl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTot)
                    .addComponent(TotHarga))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        if (optSimpati.isSelected()) {
            String sSimpati = teSimpati.getText();
            simpati = Integer.parseInt(sSimpati);
            total = total + simpati * 10000;
        } else if (optIm3.isSelected()) {
            String sIm3 = teIm3.getText();
            im3 = Integer.parseInt(sIm3);
            total = total + im3 * 9000;
        } else if (optAxis.isSelected()) {
            String sAxis = teAxis.getText();
            axis = Integer.parseInt(sAxis);
            total = total + axis * 8000;
        } else if (optXl.isSelected()) {
            String sXl = teXl.getText();
            xl = Integer.parseInt(sXl);
            total = total + xl * 7000;
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void cbMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMethodActionPerformed
        // TODO add your handling code here:
        if (cbMethod.getSelectedItem().equals("Cash")) {
            totAll = total-(0.2*total);
            TotHarga.setText(Double.toString(totAll));
        } else if (cbMethod.getSelectedItem().equals("1 Minggu")) {
            totAll = total-(0.1*total);
            TotHarga.setText(Double.toString(totAll));
        } else if (cbMethod.getSelectedItem().equals("1 Bulan")) {
            totAll = total;
            TotHarga.setText(Double.toString(totAll));
        }
    }//GEN-LAST:event_cbMethodActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        teSimpati.setText(null);
        teIm3.setText(null);
        teAxis.setText(null);
        teXl.setText(null);
        TotHarga.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KartuSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KartuSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KartuSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KartuSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KartuSim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotHarga;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cbMethod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelTot;
    private javax.swing.JCheckBox optAxis;
    private javax.swing.JCheckBox optIm3;
    private javax.swing.JCheckBox optSimpati;
    private javax.swing.JCheckBox optXl;
    private javax.swing.JTextField teAxis;
    private javax.swing.JTextField teIm3;
    private javax.swing.JTextField teSimpati;
    private javax.swing.JTextField teXl;
    // End of variables declaration//GEN-END:variables
}
